[tool.poetry]
name = "za-id-number"
version = "0.0.6"
description = "South African (RSA/ZA) Identity Number checking and validation library"
authors = ["Christo Goosen <christogoosen@gmail.com>"]
license = "MIT"
packages = [
    { include = "za_id_number" },
    { include = "za_id_number/*.py" },
    { include = "za_id_number/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
luhn = "^0.2.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-runner = "^5.2"
black = "^22.1"
bandit = "^1.7.2"

flake8 = "^4.0.1"
twine = "^3.8.0"
setuptools = "^51.3.3"
pytest-cov = "^3.0.0"
python-dateutil = "^2.8.2"
nose = "^1.3.7"
trio = "^0.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
